basic:
  site_name: 'Kremilly'
  
social_media:
  - GitHub: 'https://github.com/kremilly'
  - Leetcode: 'https://leetcode.com/kremilly'
  - Exercism: 'https://exercism.org/profiles/kremilly'
  - BlueSky: 'https://bsky.app/profile/kremilly.com'

projects:
  - Linkscraper: 'https://kremilly.github.io/Linkscraper/'
  - Scimon: 'https://scibun.github.io/ScimonDocs/'

profile:
  name: 'Kremilly'
  site_url: 'https://kremilly.com'
  avatar: 'https://avatars.githubusercontent.com/u/24691979?v=4'

google_fonts:
  - 'Montserrat:ital,wght@0,100..900;1,100..900'
  
external_js_libs:
  - 'https://code.jquery.com/jquery-3.7.1.min.js'
  - 'https://cdn.jsdelivr.net/npm/mathjax@3.2.2/es5/tex-mml-chtml.min.js'
  - 'https://cdn.jsdelivr.net/npm/lazyload@2.0.0-rc.2/lazyload.min.js'
  - 'https://cdn.jsdelivr.net/npm/sharer.js@latest/sharer.min.js'

external_css_libs:
  - 'https://use.fontawesome.com/releases/v6.5.2/css/all.css'

paths:
  contents: 
    docs: './contents/docs/'
    blog: './contents/blog/'
    pages: './contents/pages/'

  static:
    dist: './static/dist/'

    js:
      src: './static/js/src/'
      plugins: './static/js/plugins/'

    css: './static/css/'
    images: './static/images/'
