basic:
  site_name: 'Kremilly'
  domain: 'https://kremilly.com'
  
social_media:
  - GitHub: 'https://github.com/kremilly'
  - Crates: 'https://crates.io/users/Kremilly'
  - Leetcode: 'https://leetcode.com/kremilly'
  - Exercism: 'https://exercism.org/profiles/kremilly'
  - BlueSky: 'https://bsky.app/profile/kremilly.com'

projects:
  - name: 'Linkscraper'
    url: 'https://linkscraper.kremilly.com'
    description: 'Plunge into the depths of the web with Linkscraper! Uncover links, images, emails, and more swiftly, catering to researchers, developers, and curious explorers alike.'
  
  - name: 'Scimon'
    url: 'https://scimon.dev'
    description: 'Scimon is a tool designed for batch downloading PDF files using its own dedicated language, Monset (.mon). Monset features a very simple and quick-to-write syntax, making it easy to use.'
  
  - name: 'Dumpsync'
    url: 'https://dumpsync.com'
    description: 'DumpSync is a lightweight tool designed for efficiently dumping and restoring MySQL databases. Whether you need to create backups, restore databases, or transfer data between servers.'

  - name: 'ShadowJS'
    url: 'https://github.com/Gausix/ShadowJS'
    description: 'ShadowJS is a fast, lightweight JavaScript obfuscator built with Rust. It protects your code by converting readable identifiers into obscure formats, ensuring security without sacrificing performance.'
  
profile:
  name: 'Kremilly'
  site_url: 'https://kremilly.com'
  avatar: 'https://avatars.githubusercontent.com/u/24691979?v=4'

google_fonts:
  - 'Montserrat:ital,wght@0,100..900;1,100..900'
  
external_js_libs:
  - 'https://code.jquery.com/jquery-3.7.1.min.js'
  - 'https://cdn.jsdelivr.net/npm/mathjax@3.2.2/es5/tex-mml-chtml.min.js'
  - 'https://cdn.jsdelivr.net/npm/lazyload@2.0.0-rc.2/lazyload.min.js'
  - 'https://cdn.jsdelivr.net/npm/sharer.js@latest/sharer.min.js'

external_css_libs:
  - 'https://kit.fontawesome.com/5394478ac4.css'

paths:
  contents: 
    blog: './contents/'

  static:
    dist: './static/dist/'

    js:
      src: './static/js/src/'
      plugins: './static/js/plugins/'

    css: './static/css/'
    images: './static/images/'
